In [134]:
import joblib
classifier = joblib.load('svm_model.pkl')
sc = joblib.load('scaler.pkl')

In [136]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random

In [143]:
# Importing the dataset
train_data = pd.read_csv('C:/Users/roshi/Documents/1 Quaternion/3 Software/4 Python/ML/Handwritten/BackEnd/mnist_train.csv')
test_data = pd.read_csv('C:/Users/roshi/Documents/1 Quaternion/3 Software/4 Python/ML/Handwritten/BackEnd/mnist_test.csv')
X_train = train_data.iloc[:, 1:].values
y_train = train_data.iloc[:, 0].values

X_test = test_data.iloc[:, 1:].values
y_test = test_data.iloc[:, 0].values
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[5 0 4 ... 5 6 8]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[7 2 1 ... 4 5 6]


In [188]:
def predict_value(index):
	mnist_image = X_test[index]
	true_label = y_test[index]
	# print(mnist_image)
	print("True label:", true_label)
	scaled_image = sc.transform(mnist_image.reshape(1, -1))
	predicted_label = classifier.predict(scaled_image)
	print("Predicted label:", predicted_label[0])

In [223]:
predict_value(random.randint(0, len(X_test) - 1))

True label: 1
Predicted label: 1
